- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC IDs output Variable 
      include_vars: vars/vpc-output_vars

    - name: Import vprofile 
      include_vars: vars/vproStackSetup

    - name: Import SG 
      include_vars: vpro-ec2-stack.yml


    - name: Creating Nginx web01
      ec2:
        key_name: vprokey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{nginx_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "web01"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        count_tag:
          Name: "web01"
          Project: Vprofile
          Owner: DevOps Team
        group_id: "{{vproStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: web01_out